# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - effort_controller

  effort_controller:
    type: JointGroupEffortController
    # action_ns: follow_joint_trajectory
    default: true
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7